package com.pwc.hibernate;
// Generated Nov 11, 2015 11:11:59 AM by Hibernate Tools 4.0.0

/**
 * Pic generated by hbm2java
 */
public class Pic implements java.io.Serializable {

	private Integer idpic;
	private Poll poll;
	private String username;
	private String picUrl;
	private Integer picCount;
	private String pictitle;
	private String tmp1;
	private String tmp2;
	private String tmp3;
	private String tmp4;
	private String tmp5;

	public Pic() {
	}

	public Pic(Poll poll, String username, String picUrl, Integer picCount, String pictitle, String tmp1, String tmp2,
			String tmp3, String tmp4, String tmp5) {
		this.poll = poll;
		this.username = username;
		this.picUrl = picUrl;
		this.picCount = picCount;
		this.pictitle = pictitle;
		this.tmp1 = tmp1;
		this.tmp2 = tmp2;
		this.tmp3 = tmp3;
		this.tmp4 = tmp4;
		this.tmp5 = tmp5;
	}

	public Integer getIdpic() {
		return this.idpic;
	}

	public void setIdpic(Integer idpic) {
		this.idpic = idpic;
	}

	public Poll getPoll() {
		return this.poll;
	}

	public void setPoll(Poll poll) {
		this.poll = poll;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public Integer getPicCount() {
		return this.picCount;
	}

	public void setPicCount(Integer picCount) {
		this.picCount = picCount;
	}

	public String getPictitle() {
		return this.pictitle;
	}

	public void setPictitle(String pictitle) {
		this.pictitle = pictitle;
	}

	public String getTmp1() {
		return this.tmp1;
	}

	public void setTmp1(String tmp1) {
		this.tmp1 = tmp1;
	}

	public String getTmp2() {
		return this.tmp2;
	}

	public void setTmp2(String tmp2) {
		this.tmp2 = tmp2;
	}

	public String getTmp3() {
		return this.tmp3;
	}

	public void setTmp3(String tmp3) {
		this.tmp3 = tmp3;
	}

	public String getTmp4() {
		return this.tmp4;
	}

	public void setTmp4(String tmp4) {
		this.tmp4 = tmp4;
	}

	public String getTmp5() {
		return this.tmp5;
	}

	public void setTmp5(String tmp5) {
		this.tmp5 = tmp5;
	}

}
