package com.pwc.hibernate;
// Generated Nov 11, 2015 11:11:59 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Poll generated by hbm2java
 */
public class Poll implements java.io.Serializable {

	private Integer idpoll;
	private String pollTitle;
	private String pollDesc;
	private Set<Pic> pics = new HashSet<Pic>(0);

	public Poll() {
	}

	public Poll(String pollTitle, String pollDesc, Set<Pic> pics) {
		this.pollTitle = pollTitle;
		this.pollDesc = pollDesc;
		this.pics = pics;
	}

	public Integer getIdpoll() {
		return this.idpoll;
	}

	public void setIdpoll(Integer idpoll) {
		this.idpoll = idpoll;
	}

	public String getPollTitle() {
		return this.pollTitle;
	}

	public void setPollTitle(String pollTitle) {
		this.pollTitle = pollTitle;
	}

	public String getPollDesc() {
		return this.pollDesc;
	}

	public void setPollDesc(String pollDesc) {
		this.pollDesc = pollDesc;
	}

	public Set<Pic> getPics() {
		return this.pics;
	}

	public void setPics(Set<Pic> pics) {
		this.pics = pics;
	}

}
